/**
 * Comprehensive Pinyin to Wade-Giles mapping table.
 *
 * Key patterns:
 * - b → p, p → p', d → t, t → t', g → k, k → k'
 * - j → ch, q → ch', x → hs
 * - zh → ch, z → ts/tz, c → ts'/tz'
 * - Special finals: -i after zh/ch/sh/r → -ih, -i after z/c/s → -u/-zu
 */
export const PINYIN_TO_WADE_GILES: Record<string, string> = {
  // A finals
  a: "a",
  ai: "ai",
  an: "an",
  ang: "ang",
  ao: "ao",

  // B initials (→ p)
  ba: "pa",
  bai: "pai",
  ban: "pan",
  bang: "pang",
  bao: "pao",
  bei: "pei",
  ben: "pen",
  beng: "peng",
  bi: "pi",
  bian: "pien",
  biao: "piao",
  bie: "pieh",
  bin: "pin",
  bing: "ping",
  bo: "po",
  bu: "pu",

  // C initials (→ ts'/tz')
  ca: "ts'a",
  cai: "ts'ai",
  can: "ts'an",
  cang: "ts'ang",
  cao: "ts'ao",
  ce: "ts'e",
  cen: "ts'en",
  ceng: "ts'eng",
  ci: "tz'u",
  cong: "ts'ung",
  cou: "ts'ou",
  cu: "ts'u",
  cuan: "ts'uan",
  cui: "ts'ui",
  cun: "ts'un",
  cuo: "ts'o",

  // CH initials (→ ch')
  cha: "ch'a",
  chai: "ch'ai",
  chan: "ch'an",
  chang: "ch'ang",
  chao: "ch'ao",
  che: "ch'e",
  chen: "ch'en",
  cheng: "ch'eng",
  chi: "ch'ih",
  chong: "ch'ung",
  chou: "ch'ou",
  chu: "ch'u",
  chua: "ch'ua",
  chuai: "ch'uai",
  chuan: "ch'uan",
  chuang: "ch'uang",
  chui: "ch'ui",
  chun: "ch'un",
  chuo: "ch'o",

  // D initials (→ t)
  da: "ta",
  dai: "tai",
  dan: "tan",
  dang: "tang",
  dao: "tao",
  de: "te",
  dei: "tei",
  den: "ten",
  deng: "teng",
  di: "ti",
  dia: "tia",
  dian: "tien",
  diao: "tiao",
  die: "tieh",
  ding: "ting",
  diu: "tiu",
  dong: "tung",
  dou: "tou",
  du: "tu",
  duan: "tuan",
  dui: "tui",
  dun: "tun",
  duo: "to",

  // E finals
  e: "o",
  ei: "ei",
  en: "en",
  eng: "eng",
  er: "erh",

  // F initials
  fa: "fa",
  fan: "fan",
  fang: "fang",
  fei: "fei",
  fen: "fen",
  feng: "feng",
  fo: "fo",
  fou: "fou",
  fu: "fu",

  // G initials (→ k)
  ga: "ka",
  gai: "kai",
  gan: "kan",
  gang: "kang",
  gao: "kao",
  ge: "ko",
  gei: "kei",
  gen: "ken",
  geng: "keng",
  gong: "kung",
  gou: "kou",
  gu: "ku",
  gua: "kua",
  guai: "kuai",
  guan: "kuan",
  guang: "kuang",
  gui: "kuei",
  gun: "kun",
  guo: "kuo",

  // H initials
  ha: "ha",
  hai: "hai",
  han: "han",
  hang: "hang",
  hao: "hao",
  he: "ho",
  hei: "hei",
  hen: "hen",
  heng: "heng",
  hong: "hung",
  hou: "hou",
  hu: "hu",
  hua: "hua",
  huai: "huai",
  huan: "huan",
  huang: "huang",
  hui: "hui",
  hun: "hun",
  huo: "huo",

  // J initials (→ ch)
  ji: "chi",
  jia: "chia",
  jian: "chien",
  jiang: "chiang",
  jiao: "chiao",
  jie: "chieh",
  jin: "chin",
  jing: "ching",
  jiong: "chiung",
  jiu: "chiu",
  ju: "chu",
  juan: "chuan",
  jue: "chueh",
  jun: "chun",

  // K initials (→ k')
  ka: "k'a",
  kai: "k'ai",
  kan: "k'an",
  kang: "k'ang",
  kao: "k'ao",
  ke: "k'o",
  kei: "k'ei",
  ken: "k'en",
  keng: "k'eng",
  kong: "k'ung",
  kou: "k'ou",
  ku: "k'u",
  kua: "k'ua",
  kuai: "k'uai",
  kuan: "k'uan",
  kuang: "k'uang",
  kui: "k'uei",
  kun: "k'un",
  kuo: "k'uo",

  // L initials
  la: "la",
  lai: "lai",
  lan: "lan",
  lang: "lang",
  lao: "lao",
  le: "le",
  lei: "lei",
  leng: "leng",
  li: "li",
  lia: "lia",
  lian: "lien",
  liang: "liang",
  liao: "liao",
  lie: "lieh",
  lin: "lin",
  ling: "ling",
  liu: "liu",
  lo: "lo",
  long: "lung",
  lou: "lou",
  lu: "lu",
  luan: "luan",
  lun: "lun",
  luo: "lo",
  lv: "lu",
  lve: "lueh",
  lü: "lu",
  lüe: "lueh",

  // M initials
  ma: "ma",
  mai: "mai",
  man: "man",
  mang: "mang",
  mao: "mao",
  me: "me",
  mei: "mei",
  men: "men",
  meng: "meng",
  mi: "mi",
  mian: "mien",
  miao: "miao",
  mie: "mieh",
  min: "min",
  ming: "ming",
  miu: "miu",
  mo: "mo",
  mou: "mou",
  mu: "mu",

  // N initials
  na: "na",
  nai: "nai",
  nan: "nan",
  nang: "nang",
  nao: "nao",
  ne: "ne",
  nei: "nei",
  nen: "nen",
  neng: "neng",
  ni: "ni",
  nian: "nien",
  niang: "niang",
  niao: "niao",
  nie: "nieh",
  nin: "nin",
  ning: "ning",
  niu: "niu",
  nong: "nung",
  nou: "nou",
  nu: "nu",
  nuan: "nuan",
  nun: "nun",
  nuo: "no",
  nv: "nu",
  nve: "nueh",
  nü: "nu",
  nüe: "nueh",

  // O finals
  o: "o",
  ou: "ou",

  // P initials (→ p')
  pa: "p'a",
  pai: "p'ai",
  pan: "p'an",
  pang: "p'ang",
  pao: "p'ao",
  pei: "p'ei",
  pen: "p'en",
  peng: "p'eng",
  pi: "p'i",
  pian: "p'ien",
  piao: "p'iao",
  pie: "p'ieh",
  pin: "p'in",
  ping: "p'ing",
  po: "p'o",
  pou: "p'ou",
  pu: "p'u",

  // Q initials (→ ch')
  qi: "ch'i",
  qia: "ch'ia",
  qian: "ch'ien",
  qiang: "ch'iang",
  qiao: "ch'iao",
  qie: "ch'ieh",
  qin: "ch'in",
  qing: "ch'ing",
  qiong: "ch'iung",
  qiu: "ch'iu",
  qu: "ch'u",
  quan: "ch'uan",
  que: "ch'ueh",
  qun: "ch'un",

  // R initials
  ran: "jan",
  rang: "jang",
  rao: "jao",
  re: "je",
  ren: "jen",
  reng: "jeng",
  ri: "jih",
  rong: "jung",
  rou: "jou",
  ru: "ju",
  rua: "jua",
  ruan: "juan",
  rui: "jui",
  run: "jun",
  ruo: "jo",

  // S initials
  sa: "sa",
  sai: "sai",
  san: "san",
  sang: "sang",
  sao: "sao",
  se: "se",
  sen: "sen",
  seng: "seng",
  si: "ssu",
  song: "sung",
  sou: "sou",
  su: "su",
  suan: "suan",
  sui: "sui",
  sun: "sun",
  suo: "so",

  // SH initials
  sha: "sha",
  shai: "shai",
  shan: "shan",
  shang: "shang",
  shao: "shao",
  she: "she",
  shei: "shei",
  shen: "shen",
  sheng: "sheng",
  shi: "shih",
  shou: "shou",
  shu: "shu",
  shua: "shua",
  shuai: "shuai",
  shuan: "shuan",
  shuang: "shuang",
  shui: "shui",
  shun: "shun",
  shuo: "shuo",

  // T initials (→ t')
  ta: "t'a",
  tai: "t'ai",
  tan: "t'an",
  tang: "t'ang",
  tao: "t'ao",
  te: "t'e",
  tei: "t'ei",
  teng: "t'eng",
  ti: "t'i",
  tian: "t'ien",
  tiao: "t'iao",
  tie: "t'ieh",
  ting: "t'ing",
  tong: "t'ung",
  tou: "t'ou",
  tu: "t'u",
  tuan: "t'uan",
  tui: "t'ui",
  tun: "t'un",
  tuo: "t'o",

  // W initials
  wa: "wa",
  wai: "wai",
  wan: "wan",
  wang: "wang",
  wei: "wei",
  wen: "wen",
  weng: "weng",
  wo: "wo",
  wu: "wu",

  // X initials (→ hs)
  xi: "hsi",
  xia: "hsia",
  xian: "hsien",
  xiang: "hsiang",
  xiao: "hsiao",
  xie: "hsieh",
  xin: "hsin",
  xing: "hsing",
  xiong: "hsiung",
  xiu: "hsiu",
  xu: "hsu",
  xuan: "hsuan",
  xue: "hsueh",
  xun: "hsun",

  // Y initials
  ya: "ya",
  yan: "yen",
  yang: "yang",
  yao: "yao",
  ye: "yeh",
  yi: "i",
  yin: "yin",
  ying: "ying",
  yo: "yo",
  yong: "yung",
  you: "yu",
  yu: "yu",
  yuan: "yuan",
  yue: "yueh",
  yun: "yun",

  // Z initials (→ ts/tz)
  za: "tsa",
  zai: "tsai",
  zan: "tsan",
  zang: "tsang",
  zao: "tsao",
  ze: "tse",
  zei: "tsei",
  zen: "tsen",
  zeng: "tseng",
  zi: "tzu",
  zong: "tsung",
  zou: "tsou",
  zu: "tsu",
  zuan: "tsuan",
  zui: "tsui",
  zun: "tsun",
  zuo: "tso",

  // ZH initials (→ ch)
  zha: "cha",
  zhai: "chai",
  zhan: "chan",
  zhang: "chang",
  zhao: "chao",
  zhe: "che",
  zhei: "chei",
  zhen: "chen",
  zheng: "cheng",
  zhi: "chih",
  zhong: "chung",
  zhou: "chou",
  zhu: "chu",
  zhua: "chua",
  zhuai: "chuai",
  zhuan: "chuan",
  zhuang: "chuang",
  zhui: "chui",
  zhun: "chun",
  zhuo: "cho",
};

/**
 * Look up the Wade-Giles romanization for a pinyin syllable.
 * Returns undefined if not found.
 */
export function lookupWadeGiles(pinyin: string): string | undefined {
  const normalized = pinyin.toLowerCase().trim();
  return PINYIN_TO_WADE_GILES[normalized];
}
